services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  jchavez-info:
    build:
      context: .
    ports:
      - "${FRONTEND_PORT}:3004"
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgresql:5432/${DB_NAME}
      NODE_ENV: production

volumes:
  postgresql_data:
