version: '3'

services:
        jchavez_info:
                image: rex891/jchavez_info
        hot_cards:
                image: rex891/hot_cards
        nginx:
                image: nginx
                volumes:
                 - ./nginx.conf:/etc/nginx/nginx.conf:ro
                 - /etc/letsencrypt:/etc/letsencrypt
                ports:
                 - 80:80
                 - 443:443
